services:
  mariadb-zabbix:
    image: docker.io/mariadb:10
    container_name: mariadb-zabbix
    restart: unless-stopped
    environment:
      # Root password will be generated automatically and is not intended for regular use
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} # Defined in .env file
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - zabbix-net
    # Enforce UTF-8 encoding required by Zabbix (must be applied before database creation)
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_bin"

  zabbix-server:
    image: docker.io/zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    depends_on:
      - mariadb-zabbix
    environment:
      DB_SERVER_HOST: mariadb-zabbix
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "10051:10051"
    volumes:
      - zabbix-server-data:/var/lib/zabbix
      - zabbix-snmptraps-data:/var/lib/zabbix/snmptraps
      - zabbix-export-data:/var/lib/zabbix/export
    restart: unless-stopped
    networks:
      - zabbix-net

  zabbix-snmp-traps:
    image: docker.io/zabbix/zabbix-snmptraps:latest
    ports:
      # 162 is a root port
      - "1162:1162/udp"
    volumes:
      - zabbix-snmptraps-data:/var/lib/zabbix/snmptraps
    networks:
      - zabbix-net

  zabbix-web:
    image: docker.io/zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    depends_on:
      - zabbix-server
      - mariadb-zabbix
    environment:
      DB_SERVER_HOST: mariadb-zabbix
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_NAME: "ZABBIX DOCKER"
      PHP_TZ: ${PHP_TZ} # Example: "America/New_York"
    ports:
      - "8080:8080" # HTTP
      - "8443:8443" # HTTPS
    restart: unless-stopped
    #volumes:
    # - zabbix-web-data:/usr/share/zabbix
    # For HTTPS with your own certificate, uncomment and adjust:
    # - /path/to/ssl.crt:/etc/ssl/nginx/ssl.crt:ro
    # - /path/to/ssl.key:/etc/ssl/nginx/ssl.key:ro
    # - /path/to/dhparam.pem:/etc/ssl/nginx/dhparam.pem:ro
    networks:
      - zabbix-net

  zabbix-agent:
    image: docker.io/zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    depends_on:
      - zabbix-server
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: "10051"
      ZBX_HOSTNAME: "zabbix-agent"
      ZBX_SERVER_ACTIVE: zabbix-server
    restart: unless-stopped
    networks:
      - zabbix-net

volumes:
  db_data:
  # zabbix-web-data:
  zabbix-server-data:
  zabbix-snmptraps-data:
  zabbix-export-data:

networks:
  zabbix-net:
    driver: bridge
